package com.edunexus.android.feature.reports.presentation.detail

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.Share
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.edunexus.android.core.network.dto.ReportDto
import com.edunexus.android.core.ui.component.EmptyState
import com.edunexus.android.feature.reports.presentation.components.ReportCategoryBadge
import com.edunexus.android.feature.reports.presentation.components.ReportIcon
import com.edunexus.android.feature.reports.presentation.components.ReportTypeBadge

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ReportDetailScreen(
    reportId: String,
    onNavigateBack: () -> Unit,
    modifier: Modifier = Modifier,
    viewModel: ReportDetailViewModel = hiltViewModel()
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    LaunchedEffect(reportId) {
        viewModel.handleIntent(ReportDetailIntent.LoadReport(reportId))
    }

    Scaffold(
        modifier = modifier,
        topBar = {
            TopAppBar(
                title = { Text("Report Details") },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(Icons.Default.ArrowBack, "Back")
                    }
                },
                actions = {
                    IconButton(onClick = { /* Share functionality */ }) {
                        Icon(Icons.Default.Share, "Share")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.primary,
                    titleContentColor = MaterialTheme.colorScheme.onPrimary,
                    navigationIconContentColor = MaterialTheme.colorScheme.onPrimary,
                    actionIconContentColor = MaterialTheme.colorScheme.onPrimary
                )
            )
        }
    ) { paddingValues ->
        Box(Modifier.fillMaxSize().padding(paddingValues)) {
            when (val state = uiState) {
                is ReportDetailUiState.Loading -> Box(Modifier.fillMaxSize(), Alignment.Center) { CircularProgressIndicator() }
                is ReportDetailUiState.Success -> ReportDetailContent(report = state.report)
                is ReportDetailUiState.Error -> EmptyState("Error", state.message, null, "Retry", { viewModel.handleIntent(ReportDetailIntent.LoadReport(reportId)) })
            }
        }
    }
}

@Composable
private fun ReportDetailContent(report: ReportDto, modifier: Modifier = Modifier) {
    Column(
        modifier = modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp)
    ) {
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(16.dp)) {
            ReportIcon(type = report.type, size = 72.dp)
            Column(modifier = Modifier.weight(1f)) {
                Text(report.title, style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.onSurface)
                Spacer(Modifier.height(8.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    ReportTypeBadge(type = report.type)
                    ReportCategoryBadge(category = report.category)
                }
            }
        }

        Spacer(Modifier.height(24.dp))
        
        report.description?.let { desc ->
            InfoSection(title = "Description", icon = Icons.Outlined.Description) {
                Text(desc, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
            Spacer(Modifier.height(16.dp))
        }

        InfoSection(title = "Report Information", icon = Icons.Outlined.Info) {
            InfoRow("Generated By", report.generatedBy ?: "System")
            Spacer(Modifier.height(8.dp))
            InfoRow("Generated At", report.generatedAt.take(10))
        }

        report.summary?.let { summary ->
            Spacer(Modifier.height(16.dp))
            InfoSection(title = "Summary", icon = Icons.Outlined.Assessment) {
                InfoRow("Total Records", summary.totalRecords.toString())
                summary.keyMetrics?.forEach { (key, value) ->
                    Spacer(Modifier.height(8.dp))
                    InfoRow(key, value)
                }
            }
        }

        report.filters?.let { filters ->
            Spacer(Modifier.height(16.dp))
            InfoSection(title = "Filters Applied", icon = Icons.Outlined.FilterList) {
                filters.startDate?.let { InfoRow("Start Date", it); Spacer(Modifier.height(8.dp)) }
                filters.endDate?.let { InfoRow("End Date", it); Spacer(Modifier.height(8.dp)) }
                filters.classId?.let { InfoRow("Class ID", it); Spacer(Modifier.height(8.dp)) }
                filters.sectionId?.let { InfoRow("Section ID", it); Spacer(Modifier.height(8.dp)) }
                filters.departmentId?.let { InfoRow("Department ID", it) }
            }
        }
    }
}

@Composable
private fun InfoSection(title: String, icon: androidx.compose.ui.graphics.vector.ImageVector, content: @Composable ColumnScope.() -> Unit) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
    ) {
        Column(Modifier.padding(16.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Icon(icon, null, tint = MaterialTheme.colorScheme.primary, modifier = Modifier.size(24.dp))
                Text(title, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
            Spacer(Modifier.height(12.dp))
            content()
        }
    }
}

@Composable
private fun InfoRow(label: String, value: String) {
    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
        Text(label, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.Medium, color = MaterialTheme.colorScheme.onSurfaceVariant)
        Text(value, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurface)
    }
}
