import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Alert } from 'react-native';

export interface StudentReportData {
  firstName: string;
  lastName: string;
  admissionNo: string;
  class?: { name: string };
  section?: { name: string };
  rollNo?: string;
  dateOfBirth?: string;
  gender?: string;
  bloodGroup?: string;
  address?: string;
  city?: string;
  user?: {
    email?: string;
    phone?: string;
  };
}

export interface FeePaymentData {
  id: string;
  receiptNo: string;
  amount: number;
  paidAmount: number;
  fineAmount?: number;
  paymentDate: string;
  paymentMode: string;
  student: {
    firstName: string;
    lastName: string;
    admissionNo: string;
    class?: { name: string };
    section?: { name: string };
  };
  feeStructure?: {
    name: string;
    amount: number;
  };
}

export interface ExamResultData {
  exam: {
    name: string;
    date: string;
    type: string;
  };
  student: {
    firstName: string;
    lastName: string;
    admissionNo: string;
    class?: { name: string };
    section?: { name: string };
  };
  results: Array<{
    subject: { name: string };
    marksObtained: number;
    maxMarks: number;
    grade?: string;
  }>;
  totalMarks: number;
  totalMaxMarks: number;
  percentage: number;
  grade?: string;
}

export interface TimetableData {
  class: { name: string };
  section: { name: string };
  schedule: Array<{
    day: string;
    periods: Array<{
      startTime: string;
      endTime: string;
      subject: { name: string };
      teacher: { firstName: string; lastName: string };
    }>;
  }>;
}

const generateHTMLHeader = (title: string) => `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      padding: 40px;
      color: #1f2937;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
      border-bottom: 3px solid #3b82f6;
      padding-bottom: 20px;
    }
    .logo {
      font-size: 36px;
      font-weight: bold;
      color: #3b82f6;
      margin-bottom: 10px;
    }
    .school-name {
      font-size: 24px;
      font-weight: 600;
      margin-bottom: 5px;
    }
    .document-title {
      font-size: 20px;
      color: #6b7280;
      margin-top: 10px;
    }
    .info-section {
      margin: 30px 0;
    }
    .section-title {
      font-size: 18px;
      font-weight: 600;
      color: #3b82f6;
      margin-bottom: 15px;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 8px;
    }
    .info-row {
      display: flex;
      justify-content: space-between;
      padding: 10px 0;
      border-bottom: 1px solid #f3f4f6;
    }
    .info-label {
      font-weight: 500;
      color: #6b7280;
    }
    .info-value {
      font-weight: 600;
      color: #1f2937;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }
    th {
      background-color: #3b82f6;
      color: white;
      padding: 12px;
      text-align: left;
      font-weight: 600;
    }
    td {
      padding: 10px 12px;
      border-bottom: 1px solid #e5e7eb;
    }
    tr:nth-child(even) {
      background-color: #f9fafb;
    }
    .footer {
      margin-top: 50px;
      text-align: center;
      color: #6b7280;
      font-size: 12px;
      border-top: 1px solid #e5e7eb;
      padding-top: 20px;
    }
    .summary-box {
      background-color: #eff6ff;
      border: 2px solid #3b82f6;
      border-radius: 8px;
      padding: 20px;
      margin: 20px 0;
    }
    .summary-item {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
    }
    .highlight {
      color: #3b82f6;
      font-weight: 700;
      font-size: 18px;
    }
  </style>
</head>
<body>
`;

const generateHTMLFooter = () => `
  <div class="footer">
    <p>Generated by EduNexus School Management System</p>
    <p>Generated on ${new Date().toLocaleString()}</p>
  </div>
</body>
</html>
`;

export async function generateStudentReportPDF(student: StudentReportData) {
  try {
    const fullName = `${student.firstName} ${student.lastName}`;

    const html = `
      ${generateHTMLHeader('Student Report')}
      <div class="header">
        <div class="logo">EduNexus</div>
        <div class="school-name">School Management System</div>
        <div class="document-title">Student Information Report</div>
      </div>

      <div class="info-section">
        <div class="section-title">Personal Information</div>
        <div class="info-row">
          <span class="info-label">Full Name:</span>
          <span class="info-value">${fullName}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Admission No:</span>
          <span class="info-value">${student.admissionNo}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Date of Birth:</span>
          <span class="info-value">${
            student.dateOfBirth
              ? new Date(student.dateOfBirth).toLocaleDateString()
              : 'N/A'
          }</span>
        </div>
        <div class="info-row">
          <span class="info-label">Gender:</span>
          <span class="info-value">${student.gender || 'N/A'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Blood Group:</span>
          <span class="info-value">${student.bloodGroup || 'N/A'}</span>
        </div>
      </div>

      <div class="info-section">
        <div class="section-title">Academic Information</div>
        <div class="info-row">
          <span class="info-label">Class:</span>
          <span class="info-value">${student.class?.name || 'N/A'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Section:</span>
          <span class="info-value">${student.section?.name || 'N/A'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Roll No:</span>
          <span class="info-value">${student.rollNo || 'N/A'}</span>
        </div>
      </div>

      <div class="info-section">
        <div class="section-title">Contact Information</div>
        <div class="info-row">
          <span class="info-label">Email:</span>
          <span class="info-value">${student.user?.email || 'N/A'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Phone:</span>
          <span class="info-value">${student.user?.phone || 'N/A'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Address:</span>
          <span class="info-value">${student.address || 'N/A'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">City:</span>
          <span class="info-value">${student.city || 'N/A'}</span>
        </div>
      </div>

      ${generateHTMLFooter()}
    `;

    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, {
      UTI: '.pdf',
      mimeType: 'application/pdf',
    });
  } catch (error) {
    console.error('Error generating student report PDF:', error);
    Alert.alert('Error', 'Failed to generate PDF report');
  }
}

export async function generateFeeReceiptPDF(payment: FeePaymentData) {
  try {
    const studentName = `${payment.student.firstName} ${payment.student.lastName}`;

    const html = `
      ${generateHTMLHeader('Fee Receipt')}
      <div class="header">
        <div class="logo">EduNexus</div>
        <div class="school-name">School Management System</div>
        <div class="document-title">Fee Payment Receipt</div>
      </div>

      <div class="summary-box">
        <div class="summary-item">
          <span>Receipt No:</span>
          <span class="highlight">${payment.receiptNo}</span>
        </div>
        <div class="summary-item">
          <span>Date:</span>
          <span>${new Date(payment.paymentDate).toLocaleDateString()}</span>
        </div>
      </div>

      <div class="info-section">
        <div class="section-title">Student Information</div>
        <div class="info-row">
          <span class="info-label">Student Name:</span>
          <span class="info-value">${studentName}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Admission No:</span>
          <span class="info-value">${payment.student.admissionNo}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Class:</span>
          <span class="info-value">${payment.student.class?.name || 'N/A'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Section:</span>
          <span class="info-value">${payment.student.section?.name || 'N/A'}</span>
        </div>
      </div>

      <div class="info-section">
        <div class="section-title">Payment Details</div>
        <div class="info-row">
          <span class="info-label">Fee Type:</span>
          <span class="info-value">${payment.feeStructure?.name || 'N/A'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Total Amount:</span>
          <span class="info-value">₹${payment.amount.toLocaleString()}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Paid Amount:</span>
          <span class="info-value">₹${payment.paidAmount.toLocaleString()}</span>
        </div>
        ${
          payment.fineAmount
            ? `
        <div class="info-row">
          <span class="info-label">Fine Amount:</span>
          <span class="info-value">₹${payment.fineAmount.toLocaleString()}</span>
        </div>
        `
            : ''
        }
        <div class="info-row">
          <span class="info-label">Payment Mode:</span>
          <span class="info-value">${payment.paymentMode}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Payment Date:</span>
          <span class="info-value">${new Date(
            payment.paymentDate
          ).toLocaleDateString()}</span>
        </div>
      </div>

      <div class="summary-box">
        <div class="summary-item">
          <span class="highlight">Total Paid:</span>
          <span class="highlight">₹${payment.paidAmount.toLocaleString()}</span>
        </div>
      </div>

      ${generateHTMLFooter()}
    `;

    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, {
      UTI: '.pdf',
      mimeType: 'application/pdf',
    });
  } catch (error) {
    console.error('Error generating fee receipt PDF:', error);
    Alert.alert('Error', 'Failed to generate fee receipt');
  }
}

export async function generateExamResultPDF(data: ExamResultData) {
  try {
    const studentName = `${data.student.firstName} ${data.student.lastName}`;

    const resultsRows = data.results
      .map(
        (result) => `
      <tr>
        <td>${result.subject.name}</td>
        <td style="text-align: center;">${result.maxMarks}</td>
        <td style="text-align: center;">${result.marksObtained}</td>
        <td style="text-align: center;">${result.grade || '-'}</td>
      </tr>
    `
      )
      .join('');

    const html = `
      ${generateHTMLHeader('Exam Results')}
      <div class="header">
        <div class="logo">EduNexus</div>
        <div class="school-name">School Management System</div>
        <div class="document-title">Examination Report Card</div>
      </div>

      <div class="info-section">
        <div class="section-title">Student Information</div>
        <div class="info-row">
          <span class="info-label">Student Name:</span>
          <span class="info-value">${studentName}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Admission No:</span>
          <span class="info-value">${data.student.admissionNo}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Class:</span>
          <span class="info-value">${data.student.class?.name || 'N/A'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Section:</span>
          <span class="info-value">${data.student.section?.name || 'N/A'}</span>
        </div>
      </div>

      <div class="info-section">
        <div class="section-title">Exam Information</div>
        <div class="info-row">
          <span class="info-label">Exam Name:</span>
          <span class="info-value">${data.exam.name}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Exam Type:</span>
          <span class="info-value">${data.exam.type}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Date:</span>
          <span class="info-value">${new Date(
            data.exam.date
          ).toLocaleDateString()}</span>
        </div>
      </div>

      <div class="info-section">
        <div class="section-title">Subject-wise Results</div>
        <table>
          <thead>
            <tr>
              <th>Subject</th>
              <th style="text-align: center;">Max Marks</th>
              <th style="text-align: center;">Marks Obtained</th>
              <th style="text-align: center;">Grade</th>
            </tr>
          </thead>
          <tbody>
            ${resultsRows}
          </tbody>
        </table>
      </div>

      <div class="summary-box">
        <div class="summary-item">
          <span>Total Marks:</span>
          <span>${data.totalMarks} / ${data.totalMaxMarks}</span>
        </div>
        <div class="summary-item">
          <span>Percentage:</span>
          <span class="highlight">${data.percentage.toFixed(2)}%</span>
        </div>
        ${
          data.grade
            ? `
        <div class="summary-item">
          <span>Overall Grade:</span>
          <span class="highlight">${data.grade}</span>
        </div>
        `
            : ''
        }
      </div>

      ${generateHTMLFooter()}
    `;

    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, {
      UTI: '.pdf',
      mimeType: 'application/pdf',
    });
  } catch (error) {
    console.error('Error generating exam results PDF:', error);
    Alert.alert('Error', 'Failed to generate exam results PDF');
  }
}

export async function generateTimetablePDF(data: TimetableData) {
  try {
    const scheduleRows = data.schedule
      .map(
        (day) => `
      <tr>
        <td rowspan="${day.periods.length}" style="font-weight: 600; vertical-align: middle;">
          ${day.day}
        </td>
        <td>${day.periods[0].startTime} - ${day.periods[0].endTime}</td>
        <td>${day.periods[0].subject.name}</td>
        <td>${day.periods[0].teacher.firstName} ${day.periods[0].teacher.lastName}</td>
      </tr>
      ${day.periods
        .slice(1)
        .map(
          (period) => `
        <tr>
          <td>${period.startTime} - ${period.endTime}</td>
          <td>${period.subject.name}</td>
          <td>${period.teacher.firstName} ${period.teacher.lastName}</td>
        </tr>
      `
        )
        .join('')}
    `
      )
      .join('');

    const html = `
      ${generateHTMLHeader('Timetable')}
      <div class="header">
        <div class="logo">EduNexus</div>
        <div class="school-name">School Management System</div>
        <div class="document-title">Class Timetable</div>
      </div>

      <div class="info-section">
        <div class="section-title">Class Information</div>
        <div class="info-row">
          <span class="info-label">Class:</span>
          <span class="info-value">${data.class.name}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Section:</span>
          <span class="info-value">${data.section.name}</span>
        </div>
      </div>

      <div class="info-section">
        <div class="section-title">Weekly Schedule</div>
        <table>
          <thead>
            <tr>
              <th>Day</th>
              <th>Time</th>
              <th>Subject</th>
              <th>Teacher</th>
            </tr>
          </thead>
          <tbody>
            ${scheduleRows}
          </tbody>
        </table>
      </div>

      ${generateHTMLFooter()}
    `;

    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, {
      UTI: '.pdf',
      mimeType: 'application/pdf',
    });
  } catch (error) {
    console.error('Error generating timetable PDF:', error);
    Alert.alert('Error', 'Failed to generate timetable PDF');
  }
}
